//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace teste
{
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class mysurveyEntities : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto mysurveyEntities usando a cadeia de conexão localizada na seção 'mysurveyEntities' do arquivo de configuração do aplicativo.
        /// </summary>
        public mysurveyEntities() : base("name=mysurveyEntities", "mysurveyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto mysurveyEntities.
        /// </summary>
        public mysurveyEntities(string connectionString) : base(connectionString, "mysurveyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto mysurveyEntities.
        /// </summary>
        public mysurveyEntities(EntityConnection connection) : base(connection, "mysurveyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<TB_ENTREVISTADO> TB_ENTREVISTADO
        {
            get
            {
                if ((_TB_ENTREVISTADO == null))
                {
                    _TB_ENTREVISTADO = base.CreateObjectSet<TB_ENTREVISTADO>("TB_ENTREVISTADO");
                }
                return _TB_ENTREVISTADO;
            }
        }
        private ObjectSet<TB_ENTREVISTADO> _TB_ENTREVISTADO;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<TB_ITENS_DA_QUESTAO> TB_ITENS_DA_QUESTAO
        {
            get
            {
                if ((_TB_ITENS_DA_QUESTAO == null))
                {
                    _TB_ITENS_DA_QUESTAO = base.CreateObjectSet<TB_ITENS_DA_QUESTAO>("TB_ITENS_DA_QUESTAO");
                }
                return _TB_ITENS_DA_QUESTAO;
            }
        }
        private ObjectSet<TB_ITENS_DA_QUESTAO> _TB_ITENS_DA_QUESTAO;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<TB_QUESTAO> TB_QUESTAO
        {
            get
            {
                if ((_TB_QUESTAO == null))
                {
                    _TB_QUESTAO = base.CreateObjectSet<TB_QUESTAO>("TB_QUESTAO");
                }
                return _TB_QUESTAO;
            }
        }
        private ObjectSet<TB_QUESTAO> _TB_QUESTAO;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<TB_RESPONSAVEL> TB_RESPONSAVEL
        {
            get
            {
                if ((_TB_RESPONSAVEL == null))
                {
                    _TB_RESPONSAVEL = base.CreateObjectSet<TB_RESPONSAVEL>("TB_RESPONSAVEL");
                }
                return _TB_RESPONSAVEL;
            }
        }
        private ObjectSet<TB_RESPONSAVEL> _TB_RESPONSAVEL;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<TB_RESPOSTA> TB_RESPOSTA
        {
            get
            {
                if ((_TB_RESPOSTA == null))
                {
                    _TB_RESPOSTA = base.CreateObjectSet<TB_RESPOSTA>("TB_RESPOSTA");
                }
                return _TB_RESPOSTA;
            }
        }
        private ObjectSet<TB_RESPOSTA> _TB_RESPOSTA;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<TB_SURVEY> TB_SURVEY
        {
            get
            {
                if ((_TB_SURVEY == null))
                {
                    _TB_SURVEY = base.CreateObjectSet<TB_SURVEY>("TB_SURVEY");
                }
                return _TB_SURVEY;
            }
        }
        private ObjectSet<TB_SURVEY> _TB_SURVEY;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet TB_ENTREVISTADO. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToTB_ENTREVISTADO(TB_ENTREVISTADO tB_ENTREVISTADO)
        {
            base.AddObject("TB_ENTREVISTADO", tB_ENTREVISTADO);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet TB_ITENS_DA_QUESTAO. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToTB_ITENS_DA_QUESTAO(TB_ITENS_DA_QUESTAO tB_ITENS_DA_QUESTAO)
        {
            base.AddObject("TB_ITENS_DA_QUESTAO", tB_ITENS_DA_QUESTAO);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet TB_QUESTAO. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToTB_QUESTAO(TB_QUESTAO tB_QUESTAO)
        {
            base.AddObject("TB_QUESTAO", tB_QUESTAO);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet TB_RESPONSAVEL. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToTB_RESPONSAVEL(TB_RESPONSAVEL tB_RESPONSAVEL)
        {
            base.AddObject("TB_RESPONSAVEL", tB_RESPONSAVEL);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet TB_RESPOSTA. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToTB_RESPOSTA(TB_RESPOSTA tB_RESPOSTA)
        {
            base.AddObject("TB_RESPOSTA", tB_RESPOSTA);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet TB_SURVEY. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToTB_SURVEY(TB_SURVEY tB_SURVEY)
        {
            base.AddObject("TB_SURVEY", tB_SURVEY);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_ENTREVISTADO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_ENTREVISTADO : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto TB_ENTREVISTADO.
        /// </summary>
        /// <param name="idTB_ENTREVISTADO">Valor inicial da propriedade idTB_ENTREVISTADO.</param>
        public static TB_ENTREVISTADO CreateTB_ENTREVISTADO(global::System.Int32 idTB_ENTREVISTADO)
        {
            TB_ENTREVISTADO tB_ENTREVISTADO = new TB_ENTREVISTADO();
            tB_ENTREVISTADO.idTB_ENTREVISTADO = idTB_ENTREVISTADO;
            return tB_ENTREVISTADO;
        }

        #endregion

        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTB_ENTREVISTADO
        {
            get
            {
                return _idTB_ENTREVISTADO;
            }
            set
            {
                if (_idTB_ENTREVISTADO != value)
                {
                    OnidTB_ENTREVISTADOChanging(value);
                    ReportPropertyChanging("idTB_ENTREVISTADO");
                    _idTB_ENTREVISTADO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTB_ENTREVISTADO");
                    OnidTB_ENTREVISTADOChanged();
                }
            }
        }
        private global::System.Int32 _idTB_ENTREVISTADO;
        partial void OnidTB_ENTREVISTADOChanging(global::System.Int32 value);
        partial void OnidTB_ENTREVISTADOChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SOBRENOME
        {
            get
            {
                return _SOBRENOME;
            }
            set
            {
                OnSOBRENOMEChanging(value);
                ReportPropertyChanging("SOBRENOME");
                _SOBRENOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SOBRENOME");
                OnSOBRENOMEChanged();
            }
        }
        private global::System.String _SOBRENOME;
        partial void OnSOBRENOMEChanging(global::System.String value);
        partial void OnSOBRENOMEChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_ITENS_DA_QUESTAO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_ITENS_DA_QUESTAO : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto TB_ITENS_DA_QUESTAO.
        /// </summary>
        /// <param name="idTB_ITENS_DA_QUESTAO">Valor inicial da propriedade idTB_ITENS_DA_QUESTAO.</param>
        public static TB_ITENS_DA_QUESTAO CreateTB_ITENS_DA_QUESTAO(global::System.Int32 idTB_ITENS_DA_QUESTAO)
        {
            TB_ITENS_DA_QUESTAO tB_ITENS_DA_QUESTAO = new TB_ITENS_DA_QUESTAO();
            tB_ITENS_DA_QUESTAO.idTB_ITENS_DA_QUESTAO = idTB_ITENS_DA_QUESTAO;
            return tB_ITENS_DA_QUESTAO;
        }

        #endregion

        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTB_ITENS_DA_QUESTAO
        {
            get
            {
                return _idTB_ITENS_DA_QUESTAO;
            }
            set
            {
                if (_idTB_ITENS_DA_QUESTAO != value)
                {
                    OnidTB_ITENS_DA_QUESTAOChanging(value);
                    ReportPropertyChanging("idTB_ITENS_DA_QUESTAO");
                    _idTB_ITENS_DA_QUESTAO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTB_ITENS_DA_QUESTAO");
                    OnidTB_ITENS_DA_QUESTAOChanged();
                }
            }
        }
        private global::System.Int32 _idTB_ITENS_DA_QUESTAO;
        partial void OnidTB_ITENS_DA_QUESTAOChanging(global::System.Int32 value);
        partial void OnidTB_ITENS_DA_QUESTAOChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Itens
        {
            get
            {
                return _Itens;
            }
            set
            {
                OnItensChanging(value);
                ReportPropertyChanging("Itens");
                _Itens = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Itens");
                OnItensChanged();
            }
        }
        private global::System.String _Itens;
        partial void OnItensChanging(global::System.String value);
        partial void OnItensChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_QUESTAO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_QUESTAO : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto TB_QUESTAO.
        /// </summary>
        /// <param name="id_Questao">Valor inicial da propriedade id_Questao.</param>
        /// <param name="tB_SURVEY_id_Survey">Valor inicial da propriedade TB_SURVEY_id_Survey.</param>
        /// <param name="tipo">Valor inicial da propriedade Tipo.</param>
        /// <param name="pergunta">Valor inicial da propriedade Pergunta.</param>
        /// <param name="codigo">Valor inicial da propriedade Codigo.</param>
        public static TB_QUESTAO CreateTB_QUESTAO(global::System.Int32 id_Questao, global::System.Int32 tB_SURVEY_id_Survey, global::System.String tipo, global::System.String pergunta, global::System.Boolean codigo)
        {
            TB_QUESTAO tB_QUESTAO = new TB_QUESTAO();
            tB_QUESTAO.id_Questao = id_Questao;
            tB_QUESTAO.TB_SURVEY_id_Survey = tB_SURVEY_id_Survey;
            tB_QUESTAO.Tipo = tipo;
            tB_QUESTAO.Pergunta = pergunta;
            tB_QUESTAO.Codigo = codigo;
            return tB_QUESTAO;
        }

        #endregion

        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Questao
        {
            get
            {
                return _id_Questao;
            }
            set
            {
                if (_id_Questao != value)
                {
                    Onid_QuestaoChanging(value);
                    ReportPropertyChanging("id_Questao");
                    _id_Questao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Questao");
                    Onid_QuestaoChanged();
                }
            }
        }
        private global::System.Int32 _id_Questao;
        partial void Onid_QuestaoChanging(global::System.Int32 value);
        partial void Onid_QuestaoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO
        {
            get
            {
                return _TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO;
            }
            set
            {
                OnTB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAOChanging(value);
                ReportPropertyChanging("TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO");
                _TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO");
                OnTB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAOChanged();
            }
        }
        private Nullable<global::System.Int32> _TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO;
        partial void OnTB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAOChanging(Nullable<global::System.Int32> value);
        partial void OnTB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAOChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_SURVEY_id_Survey
        {
            get
            {
                return _TB_SURVEY_id_Survey;
            }
            set
            {
                OnTB_SURVEY_id_SurveyChanging(value);
                ReportPropertyChanging("TB_SURVEY_id_Survey");
                _TB_SURVEY_id_Survey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_SURVEY_id_Survey");
                OnTB_SURVEY_id_SurveyChanged();
            }
        }
        private global::System.Int32 _TB_SURVEY_id_Survey;
        partial void OnTB_SURVEY_id_SurveyChanging(global::System.Int32 value);
        partial void OnTB_SURVEY_id_SurveyChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pergunta
        {
            get
            {
                return _Pergunta;
            }
            set
            {
                OnPerguntaChanging(value);
                ReportPropertyChanging("Pergunta");
                _Pergunta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pergunta");
                OnPerguntaChanged();
            }
        }
        private global::System.String _Pergunta;
        partial void OnPerguntaChanging(global::System.String value);
        partial void OnPerguntaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Img
        {
            get
            {
                return StructuralObject.GetValidValue(_Img);
            }
            set
            {
                OnImgChanging(value);
                ReportPropertyChanging("Img");
                _Img = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Img");
                OnImgChanged();
            }
        }
        private global::System.Byte[] _Img;
        partial void OnImgChanging(global::System.Byte[] value);
        partial void OnImgChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Randomica
        {
            get
            {
                return _Randomica;
            }
            set
            {
                OnRandomicaChanging(value);
                ReportPropertyChanging("Randomica");
                _Randomica = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Randomica");
                OnRandomicaChanged();
            }
        }
        private Nullable<global::System.Boolean> _Randomica;
        partial void OnRandomicaChanging(Nullable<global::System.Boolean> value);
        partial void OnRandomicaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Obrigatoria
        {
            get
            {
                return _Obrigatoria;
            }
            set
            {
                OnObrigatoriaChanging(value);
                ReportPropertyChanging("Obrigatoria");
                _Obrigatoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Obrigatoria");
                OnObrigatoriaChanged();
            }
        }
        private Nullable<global::System.Boolean> _Obrigatoria;
        partial void OnObrigatoriaChanging(Nullable<global::System.Boolean> value);
        partial void OnObrigatoriaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.Boolean _Codigo;
        partial void OnCodigoChanging(global::System.Boolean value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Linguagem
        {
            get
            {
                return _Linguagem;
            }
            set
            {
                OnLinguagemChanging(value);
                ReportPropertyChanging("Linguagem");
                _Linguagem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Linguagem");
                OnLinguagemChanged();
            }
        }
        private global::System.String _Linguagem;
        partial void OnLinguagemChanging(global::System.String value);
        partial void OnLinguagemChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_RESPONSAVEL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_RESPONSAVEL : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto TB_RESPONSAVEL.
        /// </summary>
        /// <param name="id_Responsavel">Valor inicial da propriedade id_Responsavel.</param>
        /// <param name="nome">Valor inicial da propriedade nome.</param>
        /// <param name="email">Valor inicial da propriedade email.</param>
        /// <param name="sobrenome">Valor inicial da propriedade sobrenome.</param>
        public static TB_RESPONSAVEL CreateTB_RESPONSAVEL(global::System.Int32 id_Responsavel, global::System.String nome, global::System.String email, global::System.String sobrenome)
        {
            TB_RESPONSAVEL tB_RESPONSAVEL = new TB_RESPONSAVEL();
            tB_RESPONSAVEL.id_Responsavel = id_Responsavel;
            tB_RESPONSAVEL.nome = nome;
            tB_RESPONSAVEL.email = email;
            tB_RESPONSAVEL.sobrenome = sobrenome;
            return tB_RESPONSAVEL;
        }

        #endregion

        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Responsavel
        {
            get
            {
                return _id_Responsavel;
            }
            set
            {
                if (_id_Responsavel != value)
                {
                    Onid_ResponsavelChanging(value);
                    ReportPropertyChanging("id_Responsavel");
                    _id_Responsavel = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Responsavel");
                    Onid_ResponsavelChanged();
                }
            }
        }
        private global::System.Int32 _id_Responsavel;
        partial void Onid_ResponsavelChanging(global::System.Int32 value);
        partial void Onid_ResponsavelChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sobrenome
        {
            get
            {
                return _sobrenome;
            }
            set
            {
                OnsobrenomeChanging(value);
                ReportPropertyChanging("sobrenome");
                _sobrenome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sobrenome");
                OnsobrenomeChanged();
            }
        }
        private global::System.String _sobrenome;
        partial void OnsobrenomeChanging(global::System.String value);
        partial void OnsobrenomeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_RESPOSTA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_RESPOSTA : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto TB_RESPOSTA.
        /// </summary>
        /// <param name="id_Resposta">Valor inicial da propriedade id_Resposta.</param>
        /// <param name="tB_ENTREVISTADO_idTB_ENTREVISTADO">Valor inicial da propriedade TB_ENTREVISTADO_idTB_ENTREVISTADO.</param>
        /// <param name="tB_QUESTAO_id_Questao">Valor inicial da propriedade TB_QUESTAO_id_Questao.</param>
        public static TB_RESPOSTA CreateTB_RESPOSTA(global::System.Int32 id_Resposta, global::System.Int32 tB_ENTREVISTADO_idTB_ENTREVISTADO, global::System.Int32 tB_QUESTAO_id_Questao)
        {
            TB_RESPOSTA tB_RESPOSTA = new TB_RESPOSTA();
            tB_RESPOSTA.id_Resposta = id_Resposta;
            tB_RESPOSTA.TB_ENTREVISTADO_idTB_ENTREVISTADO = tB_ENTREVISTADO_idTB_ENTREVISTADO;
            tB_RESPOSTA.TB_QUESTAO_id_Questao = tB_QUESTAO_id_Questao;
            return tB_RESPOSTA;
        }

        #endregion

        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Resposta
        {
            get
            {
                return _id_Resposta;
            }
            set
            {
                if (_id_Resposta != value)
                {
                    Onid_RespostaChanging(value);
                    ReportPropertyChanging("id_Resposta");
                    _id_Resposta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Resposta");
                    Onid_RespostaChanged();
                }
            }
        }
        private global::System.Int32 _id_Resposta;
        partial void Onid_RespostaChanging(global::System.Int32 value);
        partial void Onid_RespostaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_ENTREVISTADO_idTB_ENTREVISTADO
        {
            get
            {
                return _TB_ENTREVISTADO_idTB_ENTREVISTADO;
            }
            set
            {
                OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanging(value);
                ReportPropertyChanging("TB_ENTREVISTADO_idTB_ENTREVISTADO");
                _TB_ENTREVISTADO_idTB_ENTREVISTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_ENTREVISTADO_idTB_ENTREVISTADO");
                OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanged();
            }
        }
        private global::System.Int32 _TB_ENTREVISTADO_idTB_ENTREVISTADO;
        partial void OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanging(global::System.Int32 value);
        partial void OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_QUESTAO_id_Questao
        {
            get
            {
                return _TB_QUESTAO_id_Questao;
            }
            set
            {
                OnTB_QUESTAO_id_QuestaoChanging(value);
                ReportPropertyChanging("TB_QUESTAO_id_Questao");
                _TB_QUESTAO_id_Questao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_QUESTAO_id_Questao");
                OnTB_QUESTAO_id_QuestaoChanged();
            }
        }
        private global::System.Int32 _TB_QUESTAO_id_Questao;
        partial void OnTB_QUESTAO_id_QuestaoChanging(global::System.Int32 value);
        partial void OnTB_QUESTAO_id_QuestaoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Resposta
        {
            get
            {
                return _Resposta;
            }
            set
            {
                OnRespostaChanging(value);
                ReportPropertyChanging("Resposta");
                _Resposta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Resposta");
                OnRespostaChanged();
            }
        }
        private global::System.String _Resposta;
        partial void OnRespostaChanging(global::System.String value);
        partial void OnRespostaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Item
        {
            get
            {
                return _Item;
            }
            set
            {
                OnItemChanging(value);
                ReportPropertyChanging("Item");
                _Item = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Item");
                OnItemChanged();
            }
        }
        private global::System.String _Item;
        partial void OnItemChanging(global::System.String value);
        partial void OnItemChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_SURVEY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_SURVEY : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto TB_SURVEY.
        /// </summary>
        /// <param name="id_Survey">Valor inicial da propriedade id_Survey.</param>
        /// <param name="tB_RESPONSAVEL_id_Responsavel">Valor inicial da propriedade TB_RESPONSAVEL_id_Responsavel.</param>
        /// <param name="titulo">Valor inicial da propriedade Titulo.</param>
        /// <param name="subtitulo">Valor inicial da propriedade Subtitulo.</param>
        public static TB_SURVEY CreateTB_SURVEY(global::System.Int32 id_Survey, global::System.Int32 tB_RESPONSAVEL_id_Responsavel, global::System.String titulo, global::System.String subtitulo)
        {
            TB_SURVEY tB_SURVEY = new TB_SURVEY();
            tB_SURVEY.id_Survey = id_Survey;
            tB_SURVEY.TB_RESPONSAVEL_id_Responsavel = tB_RESPONSAVEL_id_Responsavel;
            tB_SURVEY.Titulo = titulo;
            tB_SURVEY.Subtitulo = subtitulo;
            return tB_SURVEY;
        }

        #endregion

        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Survey
        {
            get
            {
                return _id_Survey;
            }
            set
            {
                if (_id_Survey != value)
                {
                    Onid_SurveyChanging(value);
                    ReportPropertyChanging("id_Survey");
                    _id_Survey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Survey");
                    Onid_SurveyChanged();
                }
            }
        }
        private global::System.Int32 _id_Survey;
        partial void Onid_SurveyChanging(global::System.Int32 value);
        partial void Onid_SurveyChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_RESPONSAVEL_id_Responsavel
        {
            get
            {
                return _TB_RESPONSAVEL_id_Responsavel;
            }
            set
            {
                OnTB_RESPONSAVEL_id_ResponsavelChanging(value);
                ReportPropertyChanging("TB_RESPONSAVEL_id_Responsavel");
                _TB_RESPONSAVEL_id_Responsavel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_RESPONSAVEL_id_Responsavel");
                OnTB_RESPONSAVEL_id_ResponsavelChanged();
            }
        }
        private global::System.Int32 _TB_RESPONSAVEL_id_Responsavel;
        partial void OnTB_RESPONSAVEL_id_ResponsavelChanging(global::System.Int32 value);
        partial void OnTB_RESPONSAVEL_id_ResponsavelChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subtitulo
        {
            get
            {
                return _Subtitulo;
            }
            set
            {
                OnSubtituloChanging(value);
                ReportPropertyChanging("Subtitulo");
                _Subtitulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subtitulo");
                OnSubtituloChanged();
            }
        }
        private global::System.String _Subtitulo;
        partial void OnSubtituloChanging(global::System.String value);
        partial void OnSubtituloChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantidade
        {
            get
            {
                return _Quantidade;
            }
            set
            {
                OnQuantidadeChanging(value);
                ReportPropertyChanging("Quantidade");
                _Quantidade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantidade");
                OnQuantidadeChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantidade;
        partial void OnQuantidadeChanging(Nullable<global::System.Int32> value);
        partial void OnQuantidadeChanged();

        #endregion

    
    }

    #endregion

    
}
