//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex2", "TB_ENTREVISTADO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Models.TB_ENTREVISTADO), "TB_RESPOSTA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.TB_RESPOSTA), true)]
[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_QUESTAO_FKIndex2", "TB_ITENS_DA_QUESTAO", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Models.TB_ITENS_DA_QUESTAO), "TB_QUESTAO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.TB_QUESTAO), true)]
[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_QUESTAO_FKIndex1", "TB_SURVEY", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Models.TB_SURVEY), "TB_QUESTAO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.TB_QUESTAO), true)]
[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex1", "TB_QUESTAO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Models.TB_QUESTAO), "TB_RESPOSTA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.TB_RESPOSTA), true)]
[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_SURVEY_FKIndex1", "TB_RESPONSAVEL", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Models.TB_RESPONSAVEL), "TB_SURVEY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.TB_SURVEY), true)]

#endregion

namespace Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class mysurveyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new mysurveyEntities object using the connection string found in the 'mysurveyEntities' section of the application configuration file.
        /// </summary>
        public mysurveyEntities() : base("name=mysurveyEntities", "mysurveyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mysurveyEntities object.
        /// </summary>
        public mysurveyEntities(string connectionString) : base(connectionString, "mysurveyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mysurveyEntities object.
        /// </summary>
        public mysurveyEntities(EntityConnection connection) : base(connection, "mysurveyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_ENTREVISTADO> TB_ENTREVISTADO
        {
            get
            {
                if ((_TB_ENTREVISTADO == null))
                {
                    _TB_ENTREVISTADO = base.CreateObjectSet<TB_ENTREVISTADO>("TB_ENTREVISTADO");
                }
                return _TB_ENTREVISTADO;
            }
        }
        private ObjectSet<TB_ENTREVISTADO> _TB_ENTREVISTADO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_ITENS_DA_QUESTAO> TB_ITENS_DA_QUESTAO
        {
            get
            {
                if ((_TB_ITENS_DA_QUESTAO == null))
                {
                    _TB_ITENS_DA_QUESTAO = base.CreateObjectSet<TB_ITENS_DA_QUESTAO>("TB_ITENS_DA_QUESTAO");
                }
                return _TB_ITENS_DA_QUESTAO;
            }
        }
        private ObjectSet<TB_ITENS_DA_QUESTAO> _TB_ITENS_DA_QUESTAO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_QUESTAO> TB_QUESTAO
        {
            get
            {
                if ((_TB_QUESTAO == null))
                {
                    _TB_QUESTAO = base.CreateObjectSet<TB_QUESTAO>("TB_QUESTAO");
                }
                return _TB_QUESTAO;
            }
        }
        private ObjectSet<TB_QUESTAO> _TB_QUESTAO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_RESPONSAVEL> TB_RESPONSAVEL
        {
            get
            {
                if ((_TB_RESPONSAVEL == null))
                {
                    _TB_RESPONSAVEL = base.CreateObjectSet<TB_RESPONSAVEL>("TB_RESPONSAVEL");
                }
                return _TB_RESPONSAVEL;
            }
        }
        private ObjectSet<TB_RESPONSAVEL> _TB_RESPONSAVEL;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_RESPOSTA> TB_RESPOSTA
        {
            get
            {
                if ((_TB_RESPOSTA == null))
                {
                    _TB_RESPOSTA = base.CreateObjectSet<TB_RESPOSTA>("TB_RESPOSTA");
                }
                return _TB_RESPOSTA;
            }
        }
        private ObjectSet<TB_RESPOSTA> _TB_RESPOSTA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_SURVEY> TB_SURVEY
        {
            get
            {
                if ((_TB_SURVEY == null))
                {
                    _TB_SURVEY = base.CreateObjectSet<TB_SURVEY>("TB_SURVEY");
                }
                return _TB_SURVEY;
            }
        }
        private ObjectSet<TB_SURVEY> _TB_SURVEY;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_ENTREVISTADO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_ENTREVISTADO(TB_ENTREVISTADO tB_ENTREVISTADO)
        {
            base.AddObject("TB_ENTREVISTADO", tB_ENTREVISTADO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_ITENS_DA_QUESTAO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_ITENS_DA_QUESTAO(TB_ITENS_DA_QUESTAO tB_ITENS_DA_QUESTAO)
        {
            base.AddObject("TB_ITENS_DA_QUESTAO", tB_ITENS_DA_QUESTAO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_QUESTAO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_QUESTAO(TB_QUESTAO tB_QUESTAO)
        {
            base.AddObject("TB_QUESTAO", tB_QUESTAO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_RESPONSAVEL EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_RESPONSAVEL(TB_RESPONSAVEL tB_RESPONSAVEL)
        {
            base.AddObject("TB_RESPONSAVEL", tB_RESPONSAVEL);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_RESPOSTA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_RESPOSTA(TB_RESPOSTA tB_RESPOSTA)
        {
            base.AddObject("TB_RESPOSTA", tB_RESPOSTA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_SURVEY EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_SURVEY(TB_SURVEY tB_SURVEY)
        {
            base.AddObject("TB_SURVEY", tB_SURVEY);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_ENTREVISTADO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_ENTREVISTADO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_ENTREVISTADO object.
        /// </summary>
        /// <param name="idTB_ENTREVISTADO">Initial value of the idTB_ENTREVISTADO property.</param>
        public static TB_ENTREVISTADO CreateTB_ENTREVISTADO(global::System.Int32 idTB_ENTREVISTADO)
        {
            TB_ENTREVISTADO tB_ENTREVISTADO = new TB_ENTREVISTADO();
            tB_ENTREVISTADO.idTB_ENTREVISTADO = idTB_ENTREVISTADO;
            return tB_ENTREVISTADO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTB_ENTREVISTADO
        {
            get
            {
                return _idTB_ENTREVISTADO;
            }
            set
            {
                if (_idTB_ENTREVISTADO != value)
                {
                    OnidTB_ENTREVISTADOChanging(value);
                    ReportPropertyChanging("idTB_ENTREVISTADO");
                    _idTB_ENTREVISTADO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTB_ENTREVISTADO");
                    OnidTB_ENTREVISTADOChanged();
                }
            }
        }
        private global::System.Int32 _idTB_ENTREVISTADO;
        partial void OnidTB_ENTREVISTADOChanging(global::System.Int32 value);
        partial void OnidTB_ENTREVISTADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SOBRENOME
        {
            get
            {
                return _SOBRENOME;
            }
            set
            {
                OnSOBRENOMEChanging(value);
                ReportPropertyChanging("SOBRENOME");
                _SOBRENOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SOBRENOME");
                OnSOBRENOMEChanged();
            }
        }
        private global::System.String _SOBRENOME;
        partial void OnSOBRENOMEChanging(global::System.String value);
        partial void OnSOBRENOMEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex2", "TB_RESPOSTA")]
        public EntityCollection<TB_RESPOSTA> TB_RESPOSTA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_RESPOSTA>("mysurveyModel.TB_RESPOSTA_FKIndex2", "TB_RESPOSTA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_RESPOSTA>("mysurveyModel.TB_RESPOSTA_FKIndex2", "TB_RESPOSTA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_ITENS_DA_QUESTAO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_ITENS_DA_QUESTAO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_ITENS_DA_QUESTAO object.
        /// </summary>
        /// <param name="idTB_ITENS_DA_QUESTAO">Initial value of the idTB_ITENS_DA_QUESTAO property.</param>
        /// <param name="itemA">Initial value of the ItemA property.</param>
        /// <param name="itemB">Initial value of the ItemB property.</param>
        public static TB_ITENS_DA_QUESTAO CreateTB_ITENS_DA_QUESTAO(global::System.Int32 idTB_ITENS_DA_QUESTAO, global::System.String itemA, global::System.String itemB)
        {
            TB_ITENS_DA_QUESTAO tB_ITENS_DA_QUESTAO = new TB_ITENS_DA_QUESTAO();
            tB_ITENS_DA_QUESTAO.idTB_ITENS_DA_QUESTAO = idTB_ITENS_DA_QUESTAO;
            tB_ITENS_DA_QUESTAO.ItemA = itemA;
            tB_ITENS_DA_QUESTAO.ItemB = itemB;
            return tB_ITENS_DA_QUESTAO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTB_ITENS_DA_QUESTAO
        {
            get
            {
                return _idTB_ITENS_DA_QUESTAO;
            }
            set
            {
                if (_idTB_ITENS_DA_QUESTAO != value)
                {
                    OnidTB_ITENS_DA_QUESTAOChanging(value);
                    ReportPropertyChanging("idTB_ITENS_DA_QUESTAO");
                    _idTB_ITENS_DA_QUESTAO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTB_ITENS_DA_QUESTAO");
                    OnidTB_ITENS_DA_QUESTAOChanged();
                }
            }
        }
        private global::System.Int32 _idTB_ITENS_DA_QUESTAO;
        partial void OnidTB_ITENS_DA_QUESTAOChanging(global::System.Int32 value);
        partial void OnidTB_ITENS_DA_QUESTAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemA
        {
            get
            {
                return _ItemA;
            }
            set
            {
                OnItemAChanging(value);
                ReportPropertyChanging("ItemA");
                _ItemA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemA");
                OnItemAChanged();
            }
        }
        private global::System.String _ItemA;
        partial void OnItemAChanging(global::System.String value);
        partial void OnItemAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemB
        {
            get
            {
                return _ItemB;
            }
            set
            {
                OnItemBChanging(value);
                ReportPropertyChanging("ItemB");
                _ItemB = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemB");
                OnItemBChanged();
            }
        }
        private global::System.String _ItemB;
        partial void OnItemBChanging(global::System.String value);
        partial void OnItemBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemC
        {
            get
            {
                return _ItemC;
            }
            set
            {
                OnItemCChanging(value);
                ReportPropertyChanging("ItemC");
                _ItemC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemC");
                OnItemCChanged();
            }
        }
        private global::System.String _ItemC;
        partial void OnItemCChanging(global::System.String value);
        partial void OnItemCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemD
        {
            get
            {
                return _ItemD;
            }
            set
            {
                OnItemDChanging(value);
                ReportPropertyChanging("ItemD");
                _ItemD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemD");
                OnItemDChanged();
            }
        }
        private global::System.String _ItemD;
        partial void OnItemDChanging(global::System.String value);
        partial void OnItemDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemE
        {
            get
            {
                return _ItemE;
            }
            set
            {
                OnItemEChanging(value);
                ReportPropertyChanging("ItemE");
                _ItemE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemE");
                OnItemEChanged();
            }
        }
        private global::System.String _ItemE;
        partial void OnItemEChanging(global::System.String value);
        partial void OnItemEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_QUESTAO_FKIndex2", "TB_QUESTAO")]
        public EntityCollection<TB_QUESTAO> TB_QUESTAO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_QUESTAO>("mysurveyModel.TB_QUESTAO_FKIndex2", "TB_QUESTAO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_QUESTAO>("mysurveyModel.TB_QUESTAO_FKIndex2", "TB_QUESTAO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_QUESTAO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_QUESTAO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_QUESTAO object.
        /// </summary>
        /// <param name="id_Questao">Initial value of the id_Questao property.</param>
        /// <param name="tB_SURVEY_id_Survey">Initial value of the TB_SURVEY_id_Survey property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        /// <param name="pergunta">Initial value of the Pergunta property.</param>
        /// <param name="codigo">Initial value of the Codigo property.</param>
        public static TB_QUESTAO CreateTB_QUESTAO(global::System.Int32 id_Questao, global::System.Int32 tB_SURVEY_id_Survey, global::System.String tipo, global::System.String pergunta, global::System.Boolean codigo)
        {
            TB_QUESTAO tB_QUESTAO = new TB_QUESTAO();
            tB_QUESTAO.id_Questao = id_Questao;
            tB_QUESTAO.TB_SURVEY_id_Survey = tB_SURVEY_id_Survey;
            tB_QUESTAO.Tipo = tipo;
            tB_QUESTAO.Pergunta = pergunta;
            tB_QUESTAO.Codigo = codigo;
            return tB_QUESTAO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Questao
        {
            get
            {
                return _id_Questao;
            }
            set
            {
                if (_id_Questao != value)
                {
                    Onid_QuestaoChanging(value);
                    ReportPropertyChanging("id_Questao");
                    _id_Questao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Questao");
                    Onid_QuestaoChanged();
                }
            }
        }
        private global::System.Int32 _id_Questao;
        partial void Onid_QuestaoChanging(global::System.Int32 value);
        partial void Onid_QuestaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO
        {
            get
            {
                return _TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO;
            }
            set
            {
                OnTB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAOChanging(value);
                ReportPropertyChanging("TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO");
                _TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO");
                OnTB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAOChanged();
            }
        }
        private Nullable<global::System.Int32> _TB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAO;
        partial void OnTB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAOChanging(Nullable<global::System.Int32> value);
        partial void OnTB_ITENS_DA_QUESTAO_idTB_ITENS_DA_QUESTAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_SURVEY_id_Survey
        {
            get
            {
                return _TB_SURVEY_id_Survey;
            }
            set
            {
                OnTB_SURVEY_id_SurveyChanging(value);
                ReportPropertyChanging("TB_SURVEY_id_Survey");
                _TB_SURVEY_id_Survey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_SURVEY_id_Survey");
                OnTB_SURVEY_id_SurveyChanged();
            }
        }
        private global::System.Int32 _TB_SURVEY_id_Survey;
        partial void OnTB_SURVEY_id_SurveyChanging(global::System.Int32 value);
        partial void OnTB_SURVEY_id_SurveyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pergunta
        {
            get
            {
                return _Pergunta;
            }
            set
            {
                OnPerguntaChanging(value);
                ReportPropertyChanging("Pergunta");
                _Pergunta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pergunta");
                OnPerguntaChanged();
            }
        }
        private global::System.String _Pergunta;
        partial void OnPerguntaChanging(global::System.String value);
        partial void OnPerguntaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Img
        {
            get
            {
                return StructuralObject.GetValidValue(_Img);
            }
            set
            {
                OnImgChanging(value);
                ReportPropertyChanging("Img");
                _Img = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Img");
                OnImgChanged();
            }
        }
        private global::System.Byte[] _Img;
        partial void OnImgChanging(global::System.Byte[] value);
        partial void OnImgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Randomica
        {
            get
            {
                return _Randomica;
            }
            set
            {
                OnRandomicaChanging(value);
                ReportPropertyChanging("Randomica");
                _Randomica = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Randomica");
                OnRandomicaChanged();
            }
        }
        private Nullable<global::System.Boolean> _Randomica;
        partial void OnRandomicaChanging(Nullable<global::System.Boolean> value);
        partial void OnRandomicaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Obrigatoria
        {
            get
            {
                return _Obrigatoria;
            }
            set
            {
                OnObrigatoriaChanging(value);
                ReportPropertyChanging("Obrigatoria");
                _Obrigatoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Obrigatoria");
                OnObrigatoriaChanged();
            }
        }
        private Nullable<global::System.Boolean> _Obrigatoria;
        partial void OnObrigatoriaChanging(Nullable<global::System.Boolean> value);
        partial void OnObrigatoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.Boolean _Codigo;
        partial void OnCodigoChanging(global::System.Boolean value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Linguagem
        {
            get
            {
                return _Linguagem;
            }
            set
            {
                OnLinguagemChanging(value);
                ReportPropertyChanging("Linguagem");
                _Linguagem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Linguagem");
                OnLinguagemChanged();
            }
        }
        private global::System.String _Linguagem;
        partial void OnLinguagemChanging(global::System.String value);
        partial void OnLinguagemChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_QUESTAO_FKIndex2", "TB_ITENS_DA_QUESTAO")]
        public TB_ITENS_DA_QUESTAO TB_ITENS_DA_QUESTAO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_ITENS_DA_QUESTAO>("mysurveyModel.TB_QUESTAO_FKIndex2", "TB_ITENS_DA_QUESTAO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_ITENS_DA_QUESTAO>("mysurveyModel.TB_QUESTAO_FKIndex2", "TB_ITENS_DA_QUESTAO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_ITENS_DA_QUESTAO> TB_ITENS_DA_QUESTAOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_ITENS_DA_QUESTAO>("mysurveyModel.TB_QUESTAO_FKIndex2", "TB_ITENS_DA_QUESTAO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_ITENS_DA_QUESTAO>("mysurveyModel.TB_QUESTAO_FKIndex2", "TB_ITENS_DA_QUESTAO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_QUESTAO_FKIndex1", "TB_SURVEY")]
        public TB_SURVEY TB_SURVEY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_SURVEY>("mysurveyModel.TB_QUESTAO_FKIndex1", "TB_SURVEY").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_SURVEY>("mysurveyModel.TB_QUESTAO_FKIndex1", "TB_SURVEY").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_SURVEY> TB_SURVEYReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_SURVEY>("mysurveyModel.TB_QUESTAO_FKIndex1", "TB_SURVEY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_SURVEY>("mysurveyModel.TB_QUESTAO_FKIndex1", "TB_SURVEY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex1", "TB_RESPOSTA")]
        public EntityCollection<TB_RESPOSTA> TB_RESPOSTA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_RESPOSTA>("mysurveyModel.TB_RESPOSTA_FKIndex1", "TB_RESPOSTA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_RESPOSTA>("mysurveyModel.TB_RESPOSTA_FKIndex1", "TB_RESPOSTA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_RESPONSAVEL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_RESPONSAVEL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_RESPONSAVEL object.
        /// </summary>
        /// <param name="id_Responsavel">Initial value of the id_Responsavel property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="sobrenome">Initial value of the sobrenome property.</param>
        public static TB_RESPONSAVEL CreateTB_RESPONSAVEL(global::System.Int32 id_Responsavel, global::System.String nome, global::System.String email, global::System.String sobrenome)
        {
            TB_RESPONSAVEL tB_RESPONSAVEL = new TB_RESPONSAVEL();
            tB_RESPONSAVEL.id_Responsavel = id_Responsavel;
            tB_RESPONSAVEL.nome = nome;
            tB_RESPONSAVEL.email = email;
            tB_RESPONSAVEL.sobrenome = sobrenome;
            return tB_RESPONSAVEL;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Responsavel
        {
            get
            {
                return _id_Responsavel;
            }
            set
            {
                if (_id_Responsavel != value)
                {
                    Onid_ResponsavelChanging(value);
                    ReportPropertyChanging("id_Responsavel");
                    _id_Responsavel = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Responsavel");
                    Onid_ResponsavelChanged();
                }
            }
        }
        private global::System.Int32 _id_Responsavel;
        partial void Onid_ResponsavelChanging(global::System.Int32 value);
        partial void Onid_ResponsavelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sobrenome
        {
            get
            {
                return _sobrenome;
            }
            set
            {
                OnsobrenomeChanging(value);
                ReportPropertyChanging("sobrenome");
                _sobrenome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sobrenome");
                OnsobrenomeChanged();
            }
        }
        private global::System.String _sobrenome;
        partial void OnsobrenomeChanging(global::System.String value);
        partial void OnsobrenomeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_SURVEY_FKIndex1", "TB_SURVEY")]
        public EntityCollection<TB_SURVEY> TB_SURVEY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_SURVEY>("mysurveyModel.TB_SURVEY_FKIndex1", "TB_SURVEY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_SURVEY>("mysurveyModel.TB_SURVEY_FKIndex1", "TB_SURVEY", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_RESPOSTA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_RESPOSTA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_RESPOSTA object.
        /// </summary>
        /// <param name="id_Resposta">Initial value of the id_Resposta property.</param>
        /// <param name="tB_ENTREVISTADO_idTB_ENTREVISTADO">Initial value of the TB_ENTREVISTADO_idTB_ENTREVISTADO property.</param>
        /// <param name="tB_QUESTAO_id_Questao">Initial value of the TB_QUESTAO_id_Questao property.</param>
        public static TB_RESPOSTA CreateTB_RESPOSTA(global::System.Int32 id_Resposta, global::System.Int32 tB_ENTREVISTADO_idTB_ENTREVISTADO, global::System.Int32 tB_QUESTAO_id_Questao)
        {
            TB_RESPOSTA tB_RESPOSTA = new TB_RESPOSTA();
            tB_RESPOSTA.id_Resposta = id_Resposta;
            tB_RESPOSTA.TB_ENTREVISTADO_idTB_ENTREVISTADO = tB_ENTREVISTADO_idTB_ENTREVISTADO;
            tB_RESPOSTA.TB_QUESTAO_id_Questao = tB_QUESTAO_id_Questao;
            return tB_RESPOSTA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Resposta
        {
            get
            {
                return _id_Resposta;
            }
            set
            {
                if (_id_Resposta != value)
                {
                    Onid_RespostaChanging(value);
                    ReportPropertyChanging("id_Resposta");
                    _id_Resposta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Resposta");
                    Onid_RespostaChanged();
                }
            }
        }
        private global::System.Int32 _id_Resposta;
        partial void Onid_RespostaChanging(global::System.Int32 value);
        partial void Onid_RespostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_ENTREVISTADO_idTB_ENTREVISTADO
        {
            get
            {
                return _TB_ENTREVISTADO_idTB_ENTREVISTADO;
            }
            set
            {
                OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanging(value);
                ReportPropertyChanging("TB_ENTREVISTADO_idTB_ENTREVISTADO");
                _TB_ENTREVISTADO_idTB_ENTREVISTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_ENTREVISTADO_idTB_ENTREVISTADO");
                OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanged();
            }
        }
        private global::System.Int32 _TB_ENTREVISTADO_idTB_ENTREVISTADO;
        partial void OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanging(global::System.Int32 value);
        partial void OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_QUESTAO_id_Questao
        {
            get
            {
                return _TB_QUESTAO_id_Questao;
            }
            set
            {
                OnTB_QUESTAO_id_QuestaoChanging(value);
                ReportPropertyChanging("TB_QUESTAO_id_Questao");
                _TB_QUESTAO_id_Questao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_QUESTAO_id_Questao");
                OnTB_QUESTAO_id_QuestaoChanged();
            }
        }
        private global::System.Int32 _TB_QUESTAO_id_Questao;
        partial void OnTB_QUESTAO_id_QuestaoChanging(global::System.Int32 value);
        partial void OnTB_QUESTAO_id_QuestaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Resposta
        {
            get
            {
                return _Resposta;
            }
            set
            {
                OnRespostaChanging(value);
                ReportPropertyChanging("Resposta");
                _Resposta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Resposta");
                OnRespostaChanged();
            }
        }
        private global::System.String _Resposta;
        partial void OnRespostaChanging(global::System.String value);
        partial void OnRespostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Item
        {
            get
            {
                return _Item;
            }
            set
            {
                OnItemChanging(value);
                ReportPropertyChanging("Item");
                _Item = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Item");
                OnItemChanged();
            }
        }
        private global::System.String _Item;
        partial void OnItemChanging(global::System.String value);
        partial void OnItemChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex2", "TB_ENTREVISTADO")]
        public TB_ENTREVISTADO TB_ENTREVISTADO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_ENTREVISTADO>("mysurveyModel.TB_RESPOSTA_FKIndex2", "TB_ENTREVISTADO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_ENTREVISTADO>("mysurveyModel.TB_RESPOSTA_FKIndex2", "TB_ENTREVISTADO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_ENTREVISTADO> TB_ENTREVISTADOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_ENTREVISTADO>("mysurveyModel.TB_RESPOSTA_FKIndex2", "TB_ENTREVISTADO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_ENTREVISTADO>("mysurveyModel.TB_RESPOSTA_FKIndex2", "TB_ENTREVISTADO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex1", "TB_QUESTAO")]
        public TB_QUESTAO TB_QUESTAO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_QUESTAO>("mysurveyModel.TB_RESPOSTA_FKIndex1", "TB_QUESTAO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_QUESTAO>("mysurveyModel.TB_RESPOSTA_FKIndex1", "TB_QUESTAO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_QUESTAO> TB_QUESTAOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_QUESTAO>("mysurveyModel.TB_RESPOSTA_FKIndex1", "TB_QUESTAO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_QUESTAO>("mysurveyModel.TB_RESPOSTA_FKIndex1", "TB_QUESTAO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="TB_SURVEY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_SURVEY : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_SURVEY object.
        /// </summary>
        /// <param name="id_Survey">Initial value of the id_Survey property.</param>
        /// <param name="tB_RESPONSAVEL_id_Responsavel">Initial value of the TB_RESPONSAVEL_id_Responsavel property.</param>
        /// <param name="titulo">Initial value of the Titulo property.</param>
        /// <param name="subtitulo">Initial value of the Subtitulo property.</param>
        /// <param name="data_Criacao">Initial value of the Data_Criacao property.</param>
        /// <param name="flag_ativo">Initial value of the flag_ativo property.</param>
        public static TB_SURVEY CreateTB_SURVEY(global::System.Int32 id_Survey, global::System.Int32 tB_RESPONSAVEL_id_Responsavel, global::System.String titulo, global::System.String subtitulo, global::System.DateTime data_Criacao, global::System.Boolean flag_ativo)
        {
            TB_SURVEY tB_SURVEY = new TB_SURVEY();
            tB_SURVEY.id_Survey = id_Survey;
            tB_SURVEY.TB_RESPONSAVEL_id_Responsavel = tB_RESPONSAVEL_id_Responsavel;
            tB_SURVEY.Titulo = titulo;
            tB_SURVEY.Subtitulo = subtitulo;
            tB_SURVEY.Data_Criacao = data_Criacao;
            tB_SURVEY.flag_ativo = flag_ativo;
            return tB_SURVEY;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Survey
        {
            get
            {
                return _id_Survey;
            }
            set
            {
                if (_id_Survey != value)
                {
                    Onid_SurveyChanging(value);
                    ReportPropertyChanging("id_Survey");
                    _id_Survey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Survey");
                    Onid_SurveyChanged();
                }
            }
        }
        private global::System.Int32 _id_Survey;
        partial void Onid_SurveyChanging(global::System.Int32 value);
        partial void Onid_SurveyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_RESPONSAVEL_id_Responsavel
        {
            get
            {
                return _TB_RESPONSAVEL_id_Responsavel;
            }
            set
            {
                OnTB_RESPONSAVEL_id_ResponsavelChanging(value);
                ReportPropertyChanging("TB_RESPONSAVEL_id_Responsavel");
                _TB_RESPONSAVEL_id_Responsavel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_RESPONSAVEL_id_Responsavel");
                OnTB_RESPONSAVEL_id_ResponsavelChanged();
            }
        }
        private global::System.Int32 _TB_RESPONSAVEL_id_Responsavel;
        partial void OnTB_RESPONSAVEL_id_ResponsavelChanging(global::System.Int32 value);
        partial void OnTB_RESPONSAVEL_id_ResponsavelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subtitulo
        {
            get
            {
                return _Subtitulo;
            }
            set
            {
                OnSubtituloChanging(value);
                ReportPropertyChanging("Subtitulo");
                _Subtitulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subtitulo");
                OnSubtituloChanged();
            }
        }
        private global::System.String _Subtitulo;
        partial void OnSubtituloChanging(global::System.String value);
        partial void OnSubtituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data_Criacao
        {
            get
            {
                return _Data_Criacao;
            }
            set
            {
                OnData_CriacaoChanging(value);
                ReportPropertyChanging("Data_Criacao");
                _Data_Criacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data_Criacao");
                OnData_CriacaoChanged();
            }
        }
        private global::System.DateTime _Data_Criacao;
        partial void OnData_CriacaoChanging(global::System.DateTime value);
        partial void OnData_CriacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data_fim
        {
            get
            {
                return _Data_fim;
            }
            set
            {
                OnData_fimChanging(value);
                ReportPropertyChanging("Data_fim");
                _Data_fim = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data_fim");
                OnData_fimChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data_fim;
        partial void OnData_fimChanging(Nullable<global::System.DateTime> value);
        partial void OnData_fimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean flag_ativo
        {
            get
            {
                return _flag_ativo;
            }
            set
            {
                Onflag_ativoChanging(value);
                ReportPropertyChanging("flag_ativo");
                _flag_ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("flag_ativo");
                Onflag_ativoChanged();
            }
        }
        private global::System.Boolean _flag_ativo;
        partial void Onflag_ativoChanging(global::System.Boolean value);
        partial void Onflag_ativoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_QUESTAO_FKIndex1", "TB_QUESTAO")]
        public EntityCollection<TB_QUESTAO> TB_QUESTAO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_QUESTAO>("mysurveyModel.TB_QUESTAO_FKIndex1", "TB_QUESTAO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_QUESTAO>("mysurveyModel.TB_QUESTAO_FKIndex1", "TB_QUESTAO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_SURVEY_FKIndex1", "TB_RESPONSAVEL")]
        public TB_RESPONSAVEL TB_RESPONSAVEL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_RESPONSAVEL>("mysurveyModel.TB_SURVEY_FKIndex1", "TB_RESPONSAVEL").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_RESPONSAVEL>("mysurveyModel.TB_SURVEY_FKIndex1", "TB_RESPONSAVEL").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_RESPONSAVEL> TB_RESPONSAVELReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_RESPONSAVEL>("mysurveyModel.TB_SURVEY_FKIndex1", "TB_RESPONSAVEL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_RESPONSAVEL>("mysurveyModel.TB_SURVEY_FKIndex1", "TB_RESPONSAVEL", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
