//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_CLASSE_FKIndex1", "tb_questao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Models.tb_questao), "tb_classe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.tb_classe), true)]
[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex2", "tb_entrevistado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Models.tb_entrevistado), "tb_resposta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.tb_resposta), true)]
[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_ITENS_DA_QUESTAO_FKIndex1", "tb_questao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Models.tb_questao), "tb_itens_da_questao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.tb_itens_da_questao), true)]
[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_QUESTAO_FKIndex1", "tb_survey", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Models.tb_survey), "tb_questao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.tb_questao), true)]
[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex1", "tb_questao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Models.tb_questao), "tb_resposta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.tb_resposta), true)]
[assembly: EdmRelationshipAttribute("mysurveyModel", "TB_SURVEY_FKIndex1", "tb_responsavel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Models.tb_responsavel), "tb_survey", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Models.tb_survey), true)]

#endregion

namespace Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class mysurveyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new mysurveyEntities object using the connection string found in the 'mysurveyEntities' section of the application configuration file.
        /// </summary>
        public mysurveyEntities() : base("name=mysurveyEntities", "mysurveyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mysurveyEntities object.
        /// </summary>
        public mysurveyEntities(string connectionString) : base(connectionString, "mysurveyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mysurveyEntities object.
        /// </summary>
        public mysurveyEntities(EntityConnection connection) : base(connection, "mysurveyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_classe> tb_classe
        {
            get
            {
                if ((_tb_classe == null))
                {
                    _tb_classe = base.CreateObjectSet<tb_classe>("tb_classe");
                }
                return _tb_classe;
            }
        }
        private ObjectSet<tb_classe> _tb_classe;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_entrevistado> tb_entrevistado
        {
            get
            {
                if ((_tb_entrevistado == null))
                {
                    _tb_entrevistado = base.CreateObjectSet<tb_entrevistado>("tb_entrevistado");
                }
                return _tb_entrevistado;
            }
        }
        private ObjectSet<tb_entrevistado> _tb_entrevistado;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_itens_da_questao> tb_itens_da_questao
        {
            get
            {
                if ((_tb_itens_da_questao == null))
                {
                    _tb_itens_da_questao = base.CreateObjectSet<tb_itens_da_questao>("tb_itens_da_questao");
                }
                return _tb_itens_da_questao;
            }
        }
        private ObjectSet<tb_itens_da_questao> _tb_itens_da_questao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_questao> tb_questao
        {
            get
            {
                if ((_tb_questao == null))
                {
                    _tb_questao = base.CreateObjectSet<tb_questao>("tb_questao");
                }
                return _tb_questao;
            }
        }
        private ObjectSet<tb_questao> _tb_questao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_responsavel> tb_responsavel
        {
            get
            {
                if ((_tb_responsavel == null))
                {
                    _tb_responsavel = base.CreateObjectSet<tb_responsavel>("tb_responsavel");
                }
                return _tb_responsavel;
            }
        }
        private ObjectSet<tb_responsavel> _tb_responsavel;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_resposta> tb_resposta
        {
            get
            {
                if ((_tb_resposta == null))
                {
                    _tb_resposta = base.CreateObjectSet<tb_resposta>("tb_resposta");
                }
                return _tb_resposta;
            }
        }
        private ObjectSet<tb_resposta> _tb_resposta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_survey> tb_survey
        {
            get
            {
                if ((_tb_survey == null))
                {
                    _tb_survey = base.CreateObjectSet<tb_survey>("tb_survey");
                }
                return _tb_survey;
            }
        }
        private ObjectSet<tb_survey> _tb_survey;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_classe EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_classe(tb_classe tb_classe)
        {
            base.AddObject("tb_classe", tb_classe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_entrevistado EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_entrevistado(tb_entrevistado tb_entrevistado)
        {
            base.AddObject("tb_entrevistado", tb_entrevistado);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_itens_da_questao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_itens_da_questao(tb_itens_da_questao tb_itens_da_questao)
        {
            base.AddObject("tb_itens_da_questao", tb_itens_da_questao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_questao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_questao(tb_questao tb_questao)
        {
            base.AddObject("tb_questao", tb_questao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_responsavel EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_responsavel(tb_responsavel tb_responsavel)
        {
            base.AddObject("tb_responsavel", tb_responsavel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_resposta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_resposta(tb_resposta tb_resposta)
        {
            base.AddObject("tb_resposta", tb_resposta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_survey EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_survey(tb_survey tb_survey)
        {
            base.AddObject("tb_survey", tb_survey);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="tb_classe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_classe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_classe object.
        /// </summary>
        /// <param name="id_Classe">Initial value of the id_Classe property.</param>
        /// <param name="tB_QUESTAO_id_Questao">Initial value of the TB_QUESTAO_id_Questao property.</param>
        public static tb_classe Createtb_classe(global::System.Int32 id_Classe, global::System.Int32 tB_QUESTAO_id_Questao)
        {
            tb_classe tb_classe = new tb_classe();
            tb_classe.id_Classe = id_Classe;
            tb_classe.TB_QUESTAO_id_Questao = tB_QUESTAO_id_Questao;
            return tb_classe;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Classe
        {
            get
            {
                return _id_Classe;
            }
            set
            {
                if (_id_Classe != value)
                {
                    Onid_ClasseChanging(value);
                    ReportPropertyChanging("id_Classe");
                    _id_Classe = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Classe");
                    Onid_ClasseChanged();
                }
            }
        }
        private global::System.Int32 _id_Classe;
        partial void Onid_ClasseChanging(global::System.Int32 value);
        partial void Onid_ClasseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_QUESTAO_id_Questao
        {
            get
            {
                return _TB_QUESTAO_id_Questao;
            }
            set
            {
                OnTB_QUESTAO_id_QuestaoChanging(value);
                ReportPropertyChanging("TB_QUESTAO_id_Questao");
                _TB_QUESTAO_id_Questao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_QUESTAO_id_Questao");
                OnTB_QUESTAO_id_QuestaoChanged();
            }
        }
        private global::System.Int32 _TB_QUESTAO_id_Questao;
        partial void OnTB_QUESTAO_id_QuestaoChanging(global::System.Int32 value);
        partial void OnTB_QUESTAO_id_QuestaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_CLASSE_FKIndex1", "tb_questao")]
        public tb_questao tb_questao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("mysurveyModel.TB_CLASSE_FKIndex1", "tb_questao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("mysurveyModel.TB_CLASSE_FKIndex1", "tb_questao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_questao> tb_questaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("mysurveyModel.TB_CLASSE_FKIndex1", "tb_questao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_questao>("mysurveyModel.TB_CLASSE_FKIndex1", "tb_questao", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="tb_entrevistado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_entrevistado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_entrevistado object.
        /// </summary>
        /// <param name="idTB_ENTREVISTADO">Initial value of the idTB_ENTREVISTADO property.</param>
        public static tb_entrevistado Createtb_entrevistado(global::System.Int32 idTB_ENTREVISTADO)
        {
            tb_entrevistado tb_entrevistado = new tb_entrevistado();
            tb_entrevistado.idTB_ENTREVISTADO = idTB_ENTREVISTADO;
            return tb_entrevistado;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTB_ENTREVISTADO
        {
            get
            {
                return _idTB_ENTREVISTADO;
            }
            set
            {
                if (_idTB_ENTREVISTADO != value)
                {
                    OnidTB_ENTREVISTADOChanging(value);
                    ReportPropertyChanging("idTB_ENTREVISTADO");
                    _idTB_ENTREVISTADO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTB_ENTREVISTADO");
                    OnidTB_ENTREVISTADOChanged();
                }
            }
        }
        private global::System.Int32 _idTB_ENTREVISTADO;
        partial void OnidTB_ENTREVISTADOChanging(global::System.Int32 value);
        partial void OnidTB_ENTREVISTADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SOBRENOME
        {
            get
            {
                return _SOBRENOME;
            }
            set
            {
                OnSOBRENOMEChanging(value);
                ReportPropertyChanging("SOBRENOME");
                _SOBRENOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SOBRENOME");
                OnSOBRENOMEChanged();
            }
        }
        private global::System.String _SOBRENOME;
        partial void OnSOBRENOMEChanging(global::System.String value);
        partial void OnSOBRENOMEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex2", "tb_resposta")]
        public EntityCollection<tb_resposta> tb_resposta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_resposta>("mysurveyModel.TB_RESPOSTA_FKIndex2", "tb_resposta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_resposta>("mysurveyModel.TB_RESPOSTA_FKIndex2", "tb_resposta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="tb_itens_da_questao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_itens_da_questao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_itens_da_questao object.
        /// </summary>
        /// <param name="idTB_ITENS_DA_QUESTAO">Initial value of the idTB_ITENS_DA_QUESTAO property.</param>
        /// <param name="tB_QUESTAO_id_Questao">Initial value of the TB_QUESTAO_id_Questao property.</param>
        public static tb_itens_da_questao Createtb_itens_da_questao(global::System.Int32 idTB_ITENS_DA_QUESTAO, global::System.Int32 tB_QUESTAO_id_Questao)
        {
            tb_itens_da_questao tb_itens_da_questao = new tb_itens_da_questao();
            tb_itens_da_questao.idTB_ITENS_DA_QUESTAO = idTB_ITENS_DA_QUESTAO;
            tb_itens_da_questao.TB_QUESTAO_id_Questao = tB_QUESTAO_id_Questao;
            return tb_itens_da_questao;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTB_ITENS_DA_QUESTAO
        {
            get
            {
                return _idTB_ITENS_DA_QUESTAO;
            }
            set
            {
                if (_idTB_ITENS_DA_QUESTAO != value)
                {
                    OnidTB_ITENS_DA_QUESTAOChanging(value);
                    ReportPropertyChanging("idTB_ITENS_DA_QUESTAO");
                    _idTB_ITENS_DA_QUESTAO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTB_ITENS_DA_QUESTAO");
                    OnidTB_ITENS_DA_QUESTAOChanged();
                }
            }
        }
        private global::System.Int32 _idTB_ITENS_DA_QUESTAO;
        partial void OnidTB_ITENS_DA_QUESTAOChanging(global::System.Int32 value);
        partial void OnidTB_ITENS_DA_QUESTAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_QUESTAO_id_Questao
        {
            get
            {
                return _TB_QUESTAO_id_Questao;
            }
            set
            {
                OnTB_QUESTAO_id_QuestaoChanging(value);
                ReportPropertyChanging("TB_QUESTAO_id_Questao");
                _TB_QUESTAO_id_Questao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_QUESTAO_id_Questao");
                OnTB_QUESTAO_id_QuestaoChanged();
            }
        }
        private global::System.Int32 _TB_QUESTAO_id_Questao;
        partial void OnTB_QUESTAO_id_QuestaoChanging(global::System.Int32 value);
        partial void OnTB_QUESTAO_id_QuestaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Item
        {
            get
            {
                return _Item;
            }
            set
            {
                OnItemChanging(value);
                ReportPropertyChanging("Item");
                _Item = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Item");
                OnItemChanged();
            }
        }
        private global::System.String _Item;
        partial void OnItemChanging(global::System.String value);
        partial void OnItemChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_ITENS_DA_QUESTAO_FKIndex1", "tb_questao")]
        public tb_questao tb_questao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("mysurveyModel.TB_ITENS_DA_QUESTAO_FKIndex1", "tb_questao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("mysurveyModel.TB_ITENS_DA_QUESTAO_FKIndex1", "tb_questao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_questao> tb_questaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("mysurveyModel.TB_ITENS_DA_QUESTAO_FKIndex1", "tb_questao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_questao>("mysurveyModel.TB_ITENS_DA_QUESTAO_FKIndex1", "tb_questao", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="tb_questao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_questao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_questao object.
        /// </summary>
        /// <param name="id_Questao">Initial value of the id_Questao property.</param>
        /// <param name="tB_SURVEY_id_Survey">Initial value of the TB_SURVEY_id_Survey property.</param>
        /// <param name="escolha">Initial value of the Escolha property.</param>
        /// <param name="temOutro">Initial value of the TemOutro property.</param>
        /// <param name="pergunta">Initial value of the Pergunta property.</param>
        public static tb_questao Createtb_questao(global::System.Int32 id_Questao, global::System.Int32 tB_SURVEY_id_Survey, global::System.Boolean escolha, global::System.Boolean temOutro, global::System.String pergunta)
        {
            tb_questao tb_questao = new tb_questao();
            tb_questao.id_Questao = id_Questao;
            tb_questao.TB_SURVEY_id_Survey = tB_SURVEY_id_Survey;
            tb_questao.Escolha = escolha;
            tb_questao.TemOutro = temOutro;
            tb_questao.Pergunta = pergunta;
            return tb_questao;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Questao
        {
            get
            {
                return _id_Questao;
            }
            set
            {
                if (_id_Questao != value)
                {
                    Onid_QuestaoChanging(value);
                    ReportPropertyChanging("id_Questao");
                    _id_Questao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Questao");
                    Onid_QuestaoChanged();
                }
            }
        }
        private global::System.Int32 _id_Questao;
        partial void Onid_QuestaoChanging(global::System.Int32 value);
        partial void Onid_QuestaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_SURVEY_id_Survey
        {
            get
            {
                return _TB_SURVEY_id_Survey;
            }
            set
            {
                OnTB_SURVEY_id_SurveyChanging(value);
                ReportPropertyChanging("TB_SURVEY_id_Survey");
                _TB_SURVEY_id_Survey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_SURVEY_id_Survey");
                OnTB_SURVEY_id_SurveyChanged();
            }
        }
        private global::System.Int32 _TB_SURVEY_id_Survey;
        partial void OnTB_SURVEY_id_SurveyChanging(global::System.Int32 value);
        partial void OnTB_SURVEY_id_SurveyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Escolha
        {
            get
            {
                return _Escolha;
            }
            set
            {
                OnEscolhaChanging(value);
                ReportPropertyChanging("Escolha");
                _Escolha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Escolha");
                OnEscolhaChanged();
            }
        }
        private global::System.Boolean _Escolha;
        partial void OnEscolhaChanging(global::System.Boolean value);
        partial void OnEscolhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean TemOutro
        {
            get
            {
                return _TemOutro;
            }
            set
            {
                OnTemOutroChanging(value);
                ReportPropertyChanging("TemOutro");
                _TemOutro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TemOutro");
                OnTemOutroChanged();
            }
        }
        private global::System.Boolean _TemOutro;
        partial void OnTemOutroChanging(global::System.Boolean value);
        partial void OnTemOutroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pergunta
        {
            get
            {
                return _Pergunta;
            }
            set
            {
                OnPerguntaChanging(value);
                ReportPropertyChanging("Pergunta");
                _Pergunta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pergunta");
                OnPerguntaChanged();
            }
        }
        private global::System.String _Pergunta;
        partial void OnPerguntaChanging(global::System.String value);
        partial void OnPerguntaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Img
        {
            get
            {
                return StructuralObject.GetValidValue(_Img);
            }
            set
            {
                OnImgChanging(value);
                ReportPropertyChanging("Img");
                _Img = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Img");
                OnImgChanged();
            }
        }
        private global::System.Byte[] _Img;
        partial void OnImgChanging(global::System.Byte[] value);
        partial void OnImgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Randomica
        {
            get
            {
                return _Randomica;
            }
            set
            {
                OnRandomicaChanging(value);
                ReportPropertyChanging("Randomica");
                _Randomica = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Randomica");
                OnRandomicaChanged();
            }
        }
        private Nullable<global::System.Boolean> _Randomica;
        partial void OnRandomicaChanging(Nullable<global::System.Boolean> value);
        partial void OnRandomicaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Obrigatoria
        {
            get
            {
                return _Obrigatoria;
            }
            set
            {
                OnObrigatoriaChanging(value);
                ReportPropertyChanging("Obrigatoria");
                _Obrigatoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Obrigatoria");
                OnObrigatoriaChanged();
            }
        }
        private Nullable<global::System.Boolean> _Obrigatoria;
        partial void OnObrigatoriaChanging(Nullable<global::System.Boolean> value);
        partial void OnObrigatoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EhCodigo
        {
            get
            {
                return _EhCodigo;
            }
            set
            {
                OnEhCodigoChanging(value);
                ReportPropertyChanging("EhCodigo");
                _EhCodigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EhCodigo");
                OnEhCodigoChanged();
            }
        }
        private Nullable<global::System.Boolean> _EhCodigo;
        partial void OnEhCodigoChanging(Nullable<global::System.Boolean> value);
        partial void OnEhCodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Linguagem
        {
            get
            {
                return _Linguagem;
            }
            set
            {
                OnLinguagemChanging(value);
                ReportPropertyChanging("Linguagem");
                _Linguagem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Linguagem");
                OnLinguagemChanged();
            }
        }
        private global::System.String _Linguagem;
        partial void OnLinguagemChanging(global::System.String value);
        partial void OnLinguagemChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_CLASSE_FKIndex1", "tb_classe")]
        public EntityCollection<tb_classe> tb_classe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_classe>("mysurveyModel.TB_CLASSE_FKIndex1", "tb_classe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_classe>("mysurveyModel.TB_CLASSE_FKIndex1", "tb_classe", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_ITENS_DA_QUESTAO_FKIndex1", "tb_itens_da_questao")]
        public EntityCollection<tb_itens_da_questao> tb_itens_da_questao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_itens_da_questao>("mysurveyModel.TB_ITENS_DA_QUESTAO_FKIndex1", "tb_itens_da_questao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_itens_da_questao>("mysurveyModel.TB_ITENS_DA_QUESTAO_FKIndex1", "tb_itens_da_questao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_QUESTAO_FKIndex1", "tb_survey")]
        public tb_survey tb_survey
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_survey>("mysurveyModel.TB_QUESTAO_FKIndex1", "tb_survey").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_survey>("mysurveyModel.TB_QUESTAO_FKIndex1", "tb_survey").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_survey> tb_surveyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_survey>("mysurveyModel.TB_QUESTAO_FKIndex1", "tb_survey");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_survey>("mysurveyModel.TB_QUESTAO_FKIndex1", "tb_survey", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex1", "tb_resposta")]
        public EntityCollection<tb_resposta> tb_resposta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_resposta>("mysurveyModel.TB_RESPOSTA_FKIndex1", "tb_resposta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_resposta>("mysurveyModel.TB_RESPOSTA_FKIndex1", "tb_resposta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="tb_responsavel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_responsavel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_responsavel object.
        /// </summary>
        /// <param name="id_Responsavel">Initial value of the id_Responsavel property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="sobrenome">Initial value of the sobrenome property.</param>
        public static tb_responsavel Createtb_responsavel(global::System.Int32 id_Responsavel, global::System.String nome, global::System.String email, global::System.String sobrenome)
        {
            tb_responsavel tb_responsavel = new tb_responsavel();
            tb_responsavel.id_Responsavel = id_Responsavel;
            tb_responsavel.nome = nome;
            tb_responsavel.email = email;
            tb_responsavel.sobrenome = sobrenome;
            return tb_responsavel;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Responsavel
        {
            get
            {
                return _id_Responsavel;
            }
            set
            {
                if (_id_Responsavel != value)
                {
                    Onid_ResponsavelChanging(value);
                    ReportPropertyChanging("id_Responsavel");
                    _id_Responsavel = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Responsavel");
                    Onid_ResponsavelChanged();
                }
            }
        }
        private global::System.Int32 _id_Responsavel;
        partial void Onid_ResponsavelChanging(global::System.Int32 value);
        partial void Onid_ResponsavelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sobrenome
        {
            get
            {
                return _sobrenome;
            }
            set
            {
                OnsobrenomeChanging(value);
                ReportPropertyChanging("sobrenome");
                _sobrenome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sobrenome");
                OnsobrenomeChanged();
            }
        }
        private global::System.String _sobrenome;
        partial void OnsobrenomeChanging(global::System.String value);
        partial void OnsobrenomeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_SURVEY_FKIndex1", "tb_survey")]
        public EntityCollection<tb_survey> tb_survey
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_survey>("mysurveyModel.TB_SURVEY_FKIndex1", "tb_survey");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_survey>("mysurveyModel.TB_SURVEY_FKIndex1", "tb_survey", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="tb_resposta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_resposta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_resposta object.
        /// </summary>
        /// <param name="id_Resposta">Initial value of the id_Resposta property.</param>
        /// <param name="tB_ENTREVISTADO_idTB_ENTREVISTADO">Initial value of the TB_ENTREVISTADO_idTB_ENTREVISTADO property.</param>
        /// <param name="tB_QUESTAO_id_Questao">Initial value of the TB_QUESTAO_id_Questao property.</param>
        public static tb_resposta Createtb_resposta(global::System.Int32 id_Resposta, global::System.Int32 tB_ENTREVISTADO_idTB_ENTREVISTADO, global::System.Int32 tB_QUESTAO_id_Questao)
        {
            tb_resposta tb_resposta = new tb_resposta();
            tb_resposta.id_Resposta = id_Resposta;
            tb_resposta.TB_ENTREVISTADO_idTB_ENTREVISTADO = tB_ENTREVISTADO_idTB_ENTREVISTADO;
            tb_resposta.TB_QUESTAO_id_Questao = tB_QUESTAO_id_Questao;
            return tb_resposta;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Resposta
        {
            get
            {
                return _id_Resposta;
            }
            set
            {
                if (_id_Resposta != value)
                {
                    Onid_RespostaChanging(value);
                    ReportPropertyChanging("id_Resposta");
                    _id_Resposta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Resposta");
                    Onid_RespostaChanged();
                }
            }
        }
        private global::System.Int32 _id_Resposta;
        partial void Onid_RespostaChanging(global::System.Int32 value);
        partial void Onid_RespostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_ENTREVISTADO_idTB_ENTREVISTADO
        {
            get
            {
                return _TB_ENTREVISTADO_idTB_ENTREVISTADO;
            }
            set
            {
                OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanging(value);
                ReportPropertyChanging("TB_ENTREVISTADO_idTB_ENTREVISTADO");
                _TB_ENTREVISTADO_idTB_ENTREVISTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_ENTREVISTADO_idTB_ENTREVISTADO");
                OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanged();
            }
        }
        private global::System.Int32 _TB_ENTREVISTADO_idTB_ENTREVISTADO;
        partial void OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanging(global::System.Int32 value);
        partial void OnTB_ENTREVISTADO_idTB_ENTREVISTADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_QUESTAO_id_Questao
        {
            get
            {
                return _TB_QUESTAO_id_Questao;
            }
            set
            {
                OnTB_QUESTAO_id_QuestaoChanging(value);
                ReportPropertyChanging("TB_QUESTAO_id_Questao");
                _TB_QUESTAO_id_Questao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_QUESTAO_id_Questao");
                OnTB_QUESTAO_id_QuestaoChanged();
            }
        }
        private global::System.Int32 _TB_QUESTAO_id_Questao;
        partial void OnTB_QUESTAO_id_QuestaoChanging(global::System.Int32 value);
        partial void OnTB_QUESTAO_id_QuestaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Resposta
        {
            get
            {
                return _Resposta;
            }
            set
            {
                OnRespostaChanging(value);
                ReportPropertyChanging("Resposta");
                _Resposta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Resposta");
                OnRespostaChanged();
            }
        }
        private global::System.String _Resposta;
        partial void OnRespostaChanging(global::System.String value);
        partial void OnRespostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Item
        {
            get
            {
                return _Item;
            }
            set
            {
                OnItemChanging(value);
                ReportPropertyChanging("Item");
                _Item = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Item");
                OnItemChanged();
            }
        }
        private global::System.String _Item;
        partial void OnItemChanging(global::System.String value);
        partial void OnItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OutroTxt
        {
            get
            {
                return _OutroTxt;
            }
            set
            {
                OnOutroTxtChanging(value);
                ReportPropertyChanging("OutroTxt");
                _OutroTxt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OutroTxt");
                OnOutroTxtChanged();
            }
        }
        private global::System.String _OutroTxt;
        partial void OnOutroTxtChanging(global::System.String value);
        partial void OnOutroTxtChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex2", "tb_entrevistado")]
        public tb_entrevistado tb_entrevistado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_entrevistado>("mysurveyModel.TB_RESPOSTA_FKIndex2", "tb_entrevistado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_entrevistado>("mysurveyModel.TB_RESPOSTA_FKIndex2", "tb_entrevistado").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_entrevistado> tb_entrevistadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_entrevistado>("mysurveyModel.TB_RESPOSTA_FKIndex2", "tb_entrevistado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_entrevistado>("mysurveyModel.TB_RESPOSTA_FKIndex2", "tb_entrevistado", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_RESPOSTA_FKIndex1", "tb_questao")]
        public tb_questao tb_questao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("mysurveyModel.TB_RESPOSTA_FKIndex1", "tb_questao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("mysurveyModel.TB_RESPOSTA_FKIndex1", "tb_questao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_questao> tb_questaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_questao>("mysurveyModel.TB_RESPOSTA_FKIndex1", "tb_questao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_questao>("mysurveyModel.TB_RESPOSTA_FKIndex1", "tb_questao", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mysurveyModel", Name="tb_survey")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_survey : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_survey object.
        /// </summary>
        /// <param name="id_Survey">Initial value of the id_Survey property.</param>
        /// <param name="tB_RESPONSAVEL_id_Responsavel">Initial value of the TB_RESPONSAVEL_id_Responsavel property.</param>
        /// <param name="titulo">Initial value of the Titulo property.</param>
        /// <param name="subtitulo">Initial value of the Subtitulo property.</param>
        /// <param name="data_Criacao">Initial value of the Data_Criacao property.</param>
        /// <param name="flag_ativo">Initial value of the flag_ativo property.</param>
        /// <param name="unicaResposta">Initial value of the UnicaResposta property.</param>
        /// <param name="randomizeQuestoes">Initial value of the RandomizeQuestoes property.</param>
        public static tb_survey Createtb_survey(global::System.Int32 id_Survey, global::System.Int32 tB_RESPONSAVEL_id_Responsavel, global::System.String titulo, global::System.String subtitulo, global::System.DateTime data_Criacao, global::System.Boolean flag_ativo, global::System.Boolean unicaResposta, global::System.Boolean randomizeQuestoes)
        {
            tb_survey tb_survey = new tb_survey();
            tb_survey.id_Survey = id_Survey;
            tb_survey.TB_RESPONSAVEL_id_Responsavel = tB_RESPONSAVEL_id_Responsavel;
            tb_survey.Titulo = titulo;
            tb_survey.Subtitulo = subtitulo;
            tb_survey.Data_Criacao = data_Criacao;
            tb_survey.flag_ativo = flag_ativo;
            tb_survey.UnicaResposta = unicaResposta;
            tb_survey.RandomizeQuestoes = randomizeQuestoes;
            return tb_survey;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Survey
        {
            get
            {
                return _id_Survey;
            }
            set
            {
                if (_id_Survey != value)
                {
                    Onid_SurveyChanging(value);
                    ReportPropertyChanging("id_Survey");
                    _id_Survey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Survey");
                    Onid_SurveyChanged();
                }
            }
        }
        private global::System.Int32 _id_Survey;
        partial void Onid_SurveyChanging(global::System.Int32 value);
        partial void Onid_SurveyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_RESPONSAVEL_id_Responsavel
        {
            get
            {
                return _TB_RESPONSAVEL_id_Responsavel;
            }
            set
            {
                OnTB_RESPONSAVEL_id_ResponsavelChanging(value);
                ReportPropertyChanging("TB_RESPONSAVEL_id_Responsavel");
                _TB_RESPONSAVEL_id_Responsavel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TB_RESPONSAVEL_id_Responsavel");
                OnTB_RESPONSAVEL_id_ResponsavelChanged();
            }
        }
        private global::System.Int32 _TB_RESPONSAVEL_id_Responsavel;
        partial void OnTB_RESPONSAVEL_id_ResponsavelChanging(global::System.Int32 value);
        partial void OnTB_RESPONSAVEL_id_ResponsavelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subtitulo
        {
            get
            {
                return _Subtitulo;
            }
            set
            {
                OnSubtituloChanging(value);
                ReportPropertyChanging("Subtitulo");
                _Subtitulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subtitulo");
                OnSubtituloChanged();
            }
        }
        private global::System.String _Subtitulo;
        partial void OnSubtituloChanging(global::System.String value);
        partial void OnSubtituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data_Criacao
        {
            get
            {
                return _Data_Criacao;
            }
            set
            {
                OnData_CriacaoChanging(value);
                ReportPropertyChanging("Data_Criacao");
                _Data_Criacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data_Criacao");
                OnData_CriacaoChanged();
            }
        }
        private global::System.DateTime _Data_Criacao;
        partial void OnData_CriacaoChanging(global::System.DateTime value);
        partial void OnData_CriacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data_fim
        {
            get
            {
                return _Data_fim;
            }
            set
            {
                OnData_fimChanging(value);
                ReportPropertyChanging("Data_fim");
                _Data_fim = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data_fim");
                OnData_fimChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data_fim;
        partial void OnData_fimChanging(Nullable<global::System.DateTime> value);
        partial void OnData_fimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean flag_ativo
        {
            get
            {
                return _flag_ativo;
            }
            set
            {
                Onflag_ativoChanging(value);
                ReportPropertyChanging("flag_ativo");
                _flag_ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("flag_ativo");
                Onflag_ativoChanged();
            }
        }
        private global::System.Boolean _flag_ativo;
        partial void Onflag_ativoChanging(global::System.Boolean value);
        partial void Onflag_ativoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UnicaResposta
        {
            get
            {
                return _UnicaResposta;
            }
            set
            {
                OnUnicaRespostaChanging(value);
                ReportPropertyChanging("UnicaResposta");
                _UnicaResposta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnicaResposta");
                OnUnicaRespostaChanged();
            }
        }
        private global::System.Boolean _UnicaResposta;
        partial void OnUnicaRespostaChanging(global::System.Boolean value);
        partial void OnUnicaRespostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean RandomizeQuestoes
        {
            get
            {
                return _RandomizeQuestoes;
            }
            set
            {
                OnRandomizeQuestoesChanging(value);
                ReportPropertyChanging("RandomizeQuestoes");
                _RandomizeQuestoes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RandomizeQuestoes");
                OnRandomizeQuestoesChanged();
            }
        }
        private global::System.Boolean _RandomizeQuestoes;
        partial void OnRandomizeQuestoesChanging(global::System.Boolean value);
        partial void OnRandomizeQuestoesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SenhaAcesso
        {
            get
            {
                return _SenhaAcesso;
            }
            set
            {
                OnSenhaAcessoChanging(value);
                ReportPropertyChanging("SenhaAcesso");
                _SenhaAcesso = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SenhaAcesso");
                OnSenhaAcessoChanged();
            }
        }
        private global::System.String _SenhaAcesso;
        partial void OnSenhaAcessoChanging(global::System.String value);
        partial void OnSenhaAcessoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_QUESTAO_FKIndex1", "tb_questao")]
        public EntityCollection<tb_questao> tb_questao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_questao>("mysurveyModel.TB_QUESTAO_FKIndex1", "tb_questao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_questao>("mysurveyModel.TB_QUESTAO_FKIndex1", "tb_questao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mysurveyModel", "TB_SURVEY_FKIndex1", "tb_responsavel")]
        public tb_responsavel tb_responsavel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_responsavel>("mysurveyModel.TB_SURVEY_FKIndex1", "tb_responsavel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_responsavel>("mysurveyModel.TB_SURVEY_FKIndex1", "tb_responsavel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_responsavel> tb_responsavelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_responsavel>("mysurveyModel.TB_SURVEY_FKIndex1", "tb_responsavel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_responsavel>("mysurveyModel.TB_SURVEY_FKIndex1", "tb_responsavel", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
